// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250329191118_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Danh mục Hộp bút - Túi bút chứa các sản phẩm liên quan.",
                            Name = "Hộp bút - Túi bút"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Danh mục Vở Học Sinh Campus chứa các sản phẩm liên quan.",
                            Name = "Vở Học Sinh Campus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Danh mục Bút gel chứa các sản phẩm liên quan.",
                            Name = "Bút gel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Danh mục Bút chì chứa các sản phẩm liên quan.",
                            Name = "Bút chì"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Danh mục Bút ghi nhớ chứa các sản phẩm liên quan.",
                            Name = "Bút ghi nhớ"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Danh mục Dụng cụ tẩy chứa các sản phẩm liên quan.",
                            Name = "Dụng cụ tẩy"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Danh mục Bút brush chứa các sản phẩm liên quan.",
                            Name = "Bút brush"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Danh mục Băng keo chứa các sản phẩm liên quan.",
                            Name = "Băng keo"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Danh mục Dụng cụ hỗ trợ chứa các sản phẩm liên quan.",
                            Name = "Dụng cụ hỗ trợ"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 9,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 9,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 7,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 9,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 6,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 9
                        },
                        new
                        {
                            CategoriesId = 8,
                            ProductsId = 10
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 10
                        });
                });

            modelBuilder.Entity("Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Brown"
                        });
                });

            modelBuilder.Entity("ColorProduct", b =>
                {
                    b.Property<int>("ColorsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("ColorsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ColorProduct");

                    b.HasData(
                        new
                        {
                            ColorsId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            ColorsId = 7,
                            ProductsId = 1
                        },
                        new
                        {
                            ColorsId = 10,
                            ProductsId = 1
                        },
                        new
                        {
                            ColorsId = 4,
                            ProductsId = 2
                        },
                        new
                        {
                            ColorsId = 2,
                            ProductsId = 2
                        },
                        new
                        {
                            ColorsId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            ColorsId = 4,
                            ProductsId = 3
                        },
                        new
                        {
                            ColorsId = 5,
                            ProductsId = 4
                        },
                        new
                        {
                            ColorsId = 4,
                            ProductsId = 4
                        },
                        new
                        {
                            ColorsId = 4,
                            ProductsId = 5
                        },
                        new
                        {
                            ColorsId = 10,
                            ProductsId = 5
                        },
                        new
                        {
                            ColorsId = 2,
                            ProductsId = 6
                        },
                        new
                        {
                            ColorsId = 2,
                            ProductsId = 7
                        },
                        new
                        {
                            ColorsId = 10,
                            ProductsId = 7
                        },
                        new
                        {
                            ColorsId = 5,
                            ProductsId = 8
                        },
                        new
                        {
                            ColorsId = 9,
                            ProductsId = 8
                        },
                        new
                        {
                            ColorsId = 8,
                            ProductsId = 8
                        },
                        new
                        {
                            ColorsId = 9,
                            ProductsId = 9
                        },
                        new
                        {
                            ColorsId = 11,
                            ProductsId = 10
                        },
                        new
                        {
                            ColorsId = 3,
                            ProductsId = 10
                        },
                        new
                        {
                            ColorsId = 9,
                            ProductsId = 10
                        });
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CommentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentImages");
                });

            modelBuilder.Entity("Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=942"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=539"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=845"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=708"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=220"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=935"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=359"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=27"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=937"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 1,
                            Url = "https://picsum.photos/500/500/?image=666"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=399"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=837"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=429"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=108"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=674"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=303"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=965"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=230"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=129"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 2,
                            Url = "https://picsum.photos/500/500/?image=382"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=686"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=175"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=895"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=42"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=390"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=432"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=1016"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=362"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=706"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 3,
                            Url = "https://picsum.photos/500/500/?image=493"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=485"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=916"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=969"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=370"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=201"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=96"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=40"
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=447"
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=311"
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 4,
                            Url = "https://picsum.photos/500/500/?image=122"
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=1062"
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=792"
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=702"
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=915"
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=410"
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=1060"
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=27"
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=97"
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=453"
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 5,
                            Url = "https://picsum.photos/500/500/?image=915"
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=904"
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=514"
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=579"
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=494"
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=761"
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=266"
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=253"
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=288"
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=880"
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 6,
                            Url = "https://picsum.photos/500/500/?image=599"
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=623"
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=861"
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=524"
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=368"
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=1061"
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=557"
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=451"
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=323"
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=387"
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 7,
                            Url = "https://picsum.photos/500/500/?image=502"
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=371"
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=743"
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=1004"
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=671"
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=479"
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=139"
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=522"
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=547"
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=710"
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 8,
                            Url = "https://picsum.photos/500/500/?image=112"
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=807"
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=366"
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=66"
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=392"
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=178"
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=787"
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=601"
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=887"
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=848"
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 9,
                            Url = "https://picsum.photos/500/500/?image=931"
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=128"
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=765"
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=582"
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=1049"
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=330"
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=661"
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=353"
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=1077"
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=38"
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 10,
                            Url = "https://picsum.photos/500/500/?image=882"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ShippingDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Pilot",
                            CreatedDate = new DateTime(2025, 3, 1, 15, 38, 13, 936, DateTimeKind.Local).AddTicks(3058),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Generic Wooden Fish",
                            Price = 677.879170262702500m,
                            Sold = 19,
                            StockQuantity = 75,
                            UpdatedDate = new DateTime(2025, 3, 29, 0, 22, 57, 241, DateTimeKind.Local).AddTicks(9467)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Tombow",
                            CreatedDate = new DateTime(2025, 2, 1, 17, 38, 27, 1, DateTimeKind.Local).AddTicks(7888),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Fresh Shoes",
                            Price = 419.858610433636600m,
                            Sold = 15,
                            StockQuantity = 47,
                            UpdatedDate = new DateTime(2025, 3, 8, 8, 16, 42, 294, DateTimeKind.Local).AddTicks(7262)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Stabilo",
                            CreatedDate = new DateTime(2024, 6, 12, 7, 44, 23, 611, DateTimeKind.Local).AddTicks(8195),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Fantastic Concrete Keyboard",
                            Price = 194.818832709100m,
                            Sold = 39,
                            StockQuantity = 24,
                            UpdatedDate = new DateTime(2025, 3, 25, 11, 35, 25, 905, DateTimeKind.Local).AddTicks(1926)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Marunman",
                            CreatedDate = new DateTime(2025, 1, 26, 4, 45, 42, 457, DateTimeKind.Local).AddTicks(6557),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Handmade Concrete Chips",
                            Price = 37.587966361759450m,
                            Sold = 37,
                            StockQuantity = 2,
                            UpdatedDate = new DateTime(2025, 3, 20, 7, 26, 10, 75, DateTimeKind.Local).AddTicks(8692)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Crayola",
                            CreatedDate = new DateTime(2024, 5, 13, 18, 55, 29, 210, DateTimeKind.Local).AddTicks(2517),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Practical Metal Tuna",
                            Price = 430.148605992254800m,
                            Sold = 8,
                            StockQuantity = 20,
                            UpdatedDate = new DateTime(2025, 3, 1, 21, 5, 48, 583, DateTimeKind.Local).AddTicks(6344)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Zebra",
                            CreatedDate = new DateTime(2024, 6, 21, 3, 44, 8, 291, DateTimeKind.Local).AddTicks(9787),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Unbranded Plastic Sausages",
                            Price = 14.4329001851827360m,
                            Sold = 22,
                            StockQuantity = 37,
                            UpdatedDate = new DateTime(2025, 3, 1, 4, 39, 13, 952, DateTimeKind.Local).AddTicks(1829)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Stabilo",
                            CreatedDate = new DateTime(2025, 1, 17, 8, 20, 29, 279, DateTimeKind.Local).AddTicks(4350),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Generic Plastic Chips",
                            Price = 290.272139333792800m,
                            Sold = 22,
                            StockQuantity = 78,
                            UpdatedDate = new DateTime(2025, 3, 1, 20, 45, 50, 578, DateTimeKind.Local).AddTicks(9830)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Plus",
                            CreatedDate = new DateTime(2024, 6, 30, 17, 41, 13, 245, DateTimeKind.Local).AddTicks(4500),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Tasty Frozen Pants",
                            Price = 120.986151073772600m,
                            Sold = 50,
                            StockQuantity = 30,
                            UpdatedDate = new DateTime(2025, 3, 25, 13, 36, 1, 785, DateTimeKind.Local).AddTicks(3909)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Zebra",
                            CreatedDate = new DateTime(2025, 1, 30, 19, 50, 0, 260, DateTimeKind.Local).AddTicks(4483),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Tasty Wooden Sausages",
                            Price = 171.438693553211100m,
                            Sold = 31,
                            StockQuantity = 29,
                            UpdatedDate = new DateTime(2025, 3, 14, 17, 26, 50, 153, DateTimeKind.Local).AddTicks(5150)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Kokuyo",
                            CreatedDate = new DateTime(2024, 10, 15, 1, 59, 2, 871, DateTimeKind.Local).AddTicks(3632),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Awesome Fresh Shirt",
                            Price = 273.266264993680700m,
                            Sold = 16,
                            StockQuantity = 46,
                            UpdatedDate = new DateTime(2025, 3, 10, 13, 40, 26, 613, DateTimeKind.Local).AddTicks(3770)
                        });
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.Property<int>("WishListId")
                        .HasColumnType("int");

                    b.Property<int>("WishListedByUsersId")
                        .HasColumnType("int");

                    b.HasKey("WishListId", "WishListedByUsersId");

                    b.HasIndex("WishListedByUsersId");

                    b.ToTable("ProductUser");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator role",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Description = "User role",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.HasOne("Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColorProduct", b =>
                {
                    b.HasOne("Color", null)
                        .WithMany()
                        .HasForeignKey("ColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommentImage", b =>
                {
                    b.HasOne("Comment", "Comment")
                        .WithMany("Images")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId");

                    b.HasOne("User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("WishListedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
